# Generated by Django 5.2.13 on 2026-05-05 12:47

import couples.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=couples.models.generate_invite_code, max_length=6, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_by', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
