# Generated by Django 5.2.13 on 2026-05-09 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couples', '0003_mood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='memory_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='couples.couple')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
